services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: autoservice
    ports:
      - "5432:5432"
    volumes:
      - autoservice_pg:/var/lib/postgresql/data

volumes:
  autoservice_pg:
